
"use strict";
window.ImportExport={
 normalizeWord(r,i,packId){return{id:String(r.id||`${packId}-w-${i+1}`),packId,hanzi:String(r.hanzi??r.word??"").trim(),pinyin:String(r.pinyin||"").trim(),meaning:String(r.meaning??r.translation??"").trim(),wordType:String(r.wordType||"").trim(),level:String(r.level||"").trim(),topic:String(r.topic||"").trim(),example:String(r.example||"").trim(),exampleMeaning:String(r.exampleMeaning||"").trim(),beginnerNote:String(r.beginnerNote||"").trim(),memoryTip:String(r.memoryTip||"").trim(),synonyms:Array.isArray(r.synonyms)?r.synonyms:[]}},
 parseVocab(d){const src=Array.isArray(d)?d:d?.vocabulary;if(!Array.isArray(src))throw new Error("Thiếu vocabulary.");const m=d?.meta||{},id=String(m.id||Utils.uid("vp")),errors=[],items=[],seen=new Set();src.forEach((r,i)=>{const w=this.normalizeWord(r,i,id),k=`${w.hanzi}|${w.pinyin}`;if(!w.hanzi||!w.meaning)errors.push(`Mục ${i+1}: thiếu dữ liệu`);else if(seen.has(k))errors.push(`Mục ${i+1}: trùng từ`);else{seen.add(k);items.push(w)}});if(!items.length)throw new Error("Không có từ hợp lệ.");return{kind:"vocab",pack:{id,name:String(m.name||"Bộ từ mới"),level:String(m.level||""),description:String(m.description||""),enabled:true},items,errors}},
 validateQ(q){if(!q.type)return"thiếu type";if(q.type==="reading")return q.passage&&Array.isArray(q.questions)&&q.questions.length?"":"bài đọc lỗi";if(q.type==="sentence_order")return q.answer&&Array.isArray(q.fragments)?"":"thiếu fragments";if(q.type==="writing")return q.question&&q.sampleAnswer?"":"thiếu bài mẫu";if(q.type==="error_correction")return q.question&&q.answer?"":"thiếu đáp án";if(["fill_blank","grammar"].includes(q.type))return q.options?.includes(q.answer)?"":"answer không thuộc options";if(q.type==="multiple_choice")return q.options&&Number(q.answerIndex)>=0?"":"trắc nghiệm lỗi";return"type không hỗ trợ"},
 parseQ(d){const src=Array.isArray(d)?d:d?.questions;if(!Array.isArray(src))throw new Error("Thiếu questions.");const m=d?.meta||{},id=String(m.id||Utils.uid("qp")),errors=[],items=[];src.forEach((r,i)=>{const q={...r,id:String(r.id||`${id}-q-${i+1}`),packId:id,type:String(r.type||r.category||"").trim(),level:String(r.level||m.level||"").trim()},e=this.validateQ(q);if(e)errors.push(`Câu ${i+1}: ${e}`);else items.push(q)});if(!items.length)throw new Error("Không có câu hợp lệ.");return{kind:"questions",pack:{id,name:String(m.name||"Bộ câu hỏi mới"),level:String(m.level||""),description:String(m.description||""),enabled:true},items,errors}},
 async previewVocabulary(e){const f=e.target.files?.[0];if(!f)return;try{State.pendingImport=this.parseVocab(JSON.parse(await f.text()));this.show()}catch(x){Utils.toast(x.message)}finally{e.target.value=""}},
 async previewQuestions(e){const f=e.target.files?.[0];if(!f)return;try{State.pendingImport=this.parseQ(JSON.parse(await f.text()));this.show()}catch(x){Utils.toast(x.message)}finally{e.target.value=""}},
 show(){const p=State.pendingImport;Utils.$("import-title").textContent=p.kind==="vocab"?"Nhập bộ từ":"Nhập bộ câu hỏi";Utils.$("import-summary").innerHTML=`<article class="panel"><h3>${Utils.esc(p.pack.name)}</h3><p>${p.items.length} mục hợp lệ</p><p>${p.errors.length} mục lỗi</p></article>`;Utils.$("confirm-import").onclick=()=>this.confirm();Utils.$("import-overlay").classList.add("open")},
 closePreview(e){if(e&&e.target!==Utils.$("import-overlay"))return;Utils.$("import-overlay").classList.remove("open");State.pendingImport=null},
 async confirm(){const p=State.pendingImport;if(!p)return;const ps=p.kind==="vocab"?Storage.stores.vocabPacks:Storage.stores.questionPacks,is=p.kind==="vocab"?Storage.stores.words:Storage.stores.questions;await Storage.put(ps,p.pack);for(const x of p.items)await Storage.put(is,x);this.closePreview();await Storage.loadAll();App.refresh();Vocabulary.resetFlashcards();Utils.toast("Đã nhập dữ liệu.")},
 renderPacks(){Utils.$("vocab-pack-count").textContent=`${State.vocabPacks.length} bộ`;Utils.$("question-pack-count").textContent=`${State.questionPacks.length} bộ`;Utils.$("vocab-pack-list").innerHTML=State.vocabPacks.map(p=>this.packCard(p,"vocab")).join("");Utils.$("question-pack-list").innerHTML=State.questionPacks.map(p=>this.packCard(p,"question")).join("");Utils.$("last-backup").textContent=State.settings.lastBackup?`Sao lưu gần nhất: ${new Date(State.settings.lastBackup).toLocaleString("vi-VN")}`:"Chưa có bản sao lưu."},
 packCard(p,k){const c=k==="vocab"?State.words.filter(x=>x.packId===p.id).length:State.questions.filter(x=>x.packId===p.id).length;return`<article class="pack-item"><h4>${Utils.esc(p.name)}</h4><p>${c} ${k==="vocab"?"từ":"câu"} · ${Utils.esc(p.level||"")}</p><div class="item-actions"><button class="secondary" onclick="ImportExport.togglePack('${k}','${p.id}')">${p.enabled===false?"Bật":"Tắt"}</button><button class="danger" onclick="ImportExport.deletePack('${k}','${p.id}')">Xóa</button></div></article>`},
 async togglePack(k,id){const a=k==="vocab"?State.vocabPacks:State.questionPacks,s=k==="vocab"?Storage.stores.vocabPacks:Storage.stores.questionPacks,p=a.find(x=>x.id===id);p.enabled=p.enabled===false;await Storage.put(s,p);await Storage.loadAll();App.refresh();Vocabulary.resetFlashcards()},
 async deletePack(k,id){if(!confirm("Xóa cả bộ?"))return;const a=k==="vocab"?State.words:State.questions,is=k==="vocab"?Storage.stores.words:Storage.stores.questions,ps=k==="vocab"?Storage.stores.vocabPacks:Storage.stores.questionPacks;for(const x of a.filter(x=>x.packId===id))await Storage.remove(is,x.id);await Storage.remove(ps,id);await Storage.loadAll();App.refresh();Vocabulary.resetFlashcards()},
 downloadVocabularyTemplate(){Utils.download("mau-bo-tu-vung-v2.json",{schema:"hsk-vocabulary-pack",version:2,meta:{id:"hsk4-core",name:"HSK4 - Từ vựng",level:"HSK4",description:"Bộ từ có giải thích người mới"},vocabulary:[{id:"hsk4-1",hanzi:"安排",pinyin:"ānpái",meaning:"Sắp xếp",wordType:"động từ",level:"HSK4",topic:"Công việc",example:"我安排好了。",exampleMeaning:"Tôi đã sắp xếp xong.",beginnerNote:"Dùng cho việc sắp xếp công việc, thời gian.",memoryTip:"安 + 排 = đặt mọi thứ vào vị trí."}]})},
 downloadQuestionTemplate(){Utils.download("mau-bo-cau-hoi-v2.json",DEFAULT_QUESTION_PACK)},
 exportVocabularyLibrary(){Utils.download("thu-vien-tu-vung.json",{schema:"hsk-vocabulary-library",version:2,packs:State.vocabPacks.map(p=>({meta:p,vocabulary:State.words.filter(w=>w.packId===p.id)}))})},
 exportQuestionLibrary(){Utils.download("thu-vien-cau-hoi.json",{schema:"hsk-question-library",version:2,packs:State.questionPacks.map(p=>({meta:p,questions:State.questions.filter(q=>q.packId===p.id)}))})},
 async exportBackup(){Utils.download("hsk-v2-backup.json",{schema:"hsk-v2-backup",version:2,vocabPacks:State.vocabPacks,words:State.words,questionPacks:State.questionPacks,questions:State.questions,wordProgress:[...State.wordProgress.values()],questionProgress:[...State.questionProgress.values()],activities:State.activities,settings:State.settings});await Settings.set("lastBackup",Date.now());this.renderPacks()},
 async restoreBackup(e){const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.schema!=="hsk-v2-backup")throw new Error("Sai file backup.");if(!confirm("Khôi phục sẽ ghi đè dữ liệu. Tiếp tục?"))return;await Storage.replace(Storage.stores.vocabPacks,d.vocabPacks||[]);await Storage.replace(Storage.stores.words,d.words||[]);await Storage.replace(Storage.stores.questionPacks,d.questionPacks||[]);await Storage.replace(Storage.stores.questions,d.questions||[]);await Storage.replace(Storage.stores.wordProgress,d.wordProgress||[]);await Storage.replace(Storage.stores.questionProgress,d.questionProgress||[]);await Storage.replace(Storage.stores.activities,d.activities||[]);await Storage.replace(Storage.stores.settings,Object.entries(d.settings||{}).map(([key,value])=>({key,value})));await Storage.loadAll();App.refresh();Vocabulary.resetFlashcards();Utils.toast("Đã khôi phục.")}catch(x){Utils.toast(x.message)}finally{e.target.value=""}}
};
