
"use strict";
window.Learning={
 async log(kind,targetId,correct,category=""){const a={id:Utils.uid("act"),kind,targetId,correct,category,timestamp:Date.now()};State.activities.unshift(a);await Storage.put(Storage.stores.activities,a)},
 startSmartSession(){const items=[];Utils.shuffle(Vocabulary.activeWords()).slice(0,8).forEach((w,i)=>items.push({kind:i%2?"wordQuiz":"flashcard",word:w}));Practice.select("mixed",10,"smart","all").forEach(q=>items.push({kind:"question",question:q}));if(!items.length)return Utils.toast("Chưa có dữ liệu.");State.session={items:Utils.shuffle(items),index:0,correct:0};App.showScreen("session");this.render()},
 startQuestionSession(qs){if(!qs.length)return Utils.toast("Không có câu phù hợp.");State.session={items:qs.map(q=>({kind:"question",question:q})),index:0,correct:0};App.showScreen("session");this.render()},
 exitSession(){if(confirm("Thoát buổi học?")){State.session=null;App.showScreen("home")}},
 render(){if(!State.session||State.session.index>=State.session.items.length)return this.finish();Utils.$("session-step").textContent=`${State.session.index+1}/${State.session.items.length}`;Utils.$("session-progress").style.width=`${State.session.index/State.session.items.length*100}%`;const x=State.session.items[State.session.index];if(x.kind==="flashcard")this.renderFlash(x.word);else if(x.kind==="wordQuiz")this.renderWordQuiz(x.word);else this.renderQuestion(x.question)},
 renderFlash(w){Utils.$("session-content").innerHTML=`<article class="question-card center"><span class="badge">FLASHCARD</span><div class="hanzi">${Utils.esc(w.hanzi)}</div><div class="pinyin">${Utils.esc(w.pinyin)}</div><div class="meaning">${Utils.esc(w.meaning)}</div><div class="rating-grid"><button class="danger" onclick="Learning.answerFlash(0)">Quên</button><button class="warning" onclick="Learning.answerFlash(2)">Khó</button><button onclick="Learning.answerFlash(4)">Nhớ</button><button class="success" onclick="Learning.answerFlash(5)">Rất dễ</button></div></article>`},
 async answerFlash(q){const w=State.session.items[State.session.index].word;await Vocabulary.saveProgress(Vocabulary.calculate(Vocabulary.getProgress(w.id),q));if(q>=3)State.session.correct++;await this.log("word",w.id,q>=3,w.level);State.session.index++;this.render()},
 renderWordQuiz(w){const o=Utils.shuffle([w,...Utils.shuffle(Vocabulary.activeWords().filter(x=>x.id!==w.id)).slice(0,3)]);Utils.$("session-content").innerHTML=`<article class="question-card"><span class="badge">CHỌN NGHĨA</span><h2 class="center">${Utils.esc(w.hanzi)}</h2><div class="option-grid">${o.map(x=>`<button onclick="Learning.answerWordQuiz(this,'${x.id}','${w.id}')">${Utils.esc(x.meaning)}</button>`).join("")}</div></article>`},
 async answerWordQuiz(btn,id,correct){const ok=id===correct;document.querySelectorAll(".option-grid button").forEach(b=>b.disabled=true);btn.classList.add(ok?"correct":"wrong");const w=State.session.items[State.session.index].word,p={...Vocabulary.getProgress(w.id)};p[ok?"correct":"incorrect"]++;p.lastStudied=Date.now();await Vocabulary.saveProgress(p);if(ok)State.session.correct++;await this.log("word",w.id,ok,w.level);setTimeout(()=>{State.session.index++;this.render()},600)},
 renderQuestion(q){if(q.type==="reading")return this.renderReading(q);if(["sentence_order","writing","error_correction"].includes(q.type))return this.renderOpen(q);const ai=q.type==="multiple_choice"?Number(q.answerIndex):q.options.indexOf(q.answer);Utils.$("session-content").innerHTML=`<article class="question-card"><span class="badge">${Utils.esc(Statistics.typeLabel(q.type))}</span>${q.grammarPoint?`<p class="muted">${Utils.esc(q.grammarPoint)}</p>`:""}<h2>${Utils.esc(q.question)}</h2><div class="option-grid">${q.options.map((o,i)=>`<button onclick="Learning.answerOption(this,${i},${ai})">${Utils.esc(o)}</button>`).join("")}</div><div id="feedback"></div></article>`},
 renderReading(q){const s=q.questions[0];Utils.$("session-content").innerHTML=`<article class="question-card"><span class="badge">ĐỌC HIỂU</span><h2>${Utils.esc(q.title||"Bài đọc")}</h2><p class="answer-box">${Utils.esc(q.passage)}</p><details><summary>Xem bản dịch</summary><p>${Utils.esc(q.translation||"")}</p></details><h3>${Utils.esc(s.question)}</h3><div class="option-grid">${s.options.map((o,i)=>`<button onclick="Learning.answerOption(this,${i},${Number(s.answerIndex)},true)">${Utils.esc(o)}</button>`).join("")}</div><div id="feedback"></div></article>`},
 renderOpen(q){Utils.$("session-content").innerHTML=`<article class="question-card"><span class="badge">${Utils.esc(Statistics.typeLabel(q.type))}</span><h2>${Utils.esc(q.question)}</h2>${q.fragments?`<div>${q.fragments.map(x=>`<span class="fragment">${Utils.esc(x)}</span>`).join("")}</div>`:""}${q.requiredWords?`<p>Từ bắt buộc: ${q.requiredWords.map(Utils.esc).join(" · ")}</p>`:""}<textarea rows="5"></textarea><button class="full" onclick="Learning.reveal()">Xem đáp án</button><div id="feedback"></div></article>`},
 answerOption(btn,i,a,isReading=false){const q=State.session.items[State.session.index].question,ok=i===a;document.querySelectorAll(".option-grid button").forEach((b,idx)=>{b.disabled=true;if(idx===a)b.classList.add("correct")});if(!ok)btn.classList.add("wrong");const s=isReading?q.questions[0]:q;const beginner=State.settings.beginnerMode!==false&&(q.beginnerExplanation||s.beginnerExplanation)?`<p><strong>Giải thích cho người mới:</strong> ${Utils.esc(q.beginnerExplanation||s.beginnerExplanation)}</p>`:"";Utils.$("feedback").innerHTML=`<div class="answer-box"><strong>${ok?"Chính xác":"Chưa đúng"}</strong><p>${Utils.esc(s.explanation||"")}</p>${beginner}</div><button class="full" onclick="Learning.nextQuestion(${ok})">Câu tiếp theo</button>`},
 reveal(){const q=State.session.items[State.session.index].question;Utils.$("feedback").innerHTML=`<div class="answer-box"><strong>Đáp án</strong><p>${Utils.esc(q.answer||q.sampleAnswer||"")}</p><p>${Utils.esc(q.explanation||"")}</p></div><div class="button-row"><button class="danger" onclick="Learning.nextQuestion(false)">Chưa đạt</button><button class="success" onclick="Learning.nextQuestion(true)">Đã hiểu</button></div>`},
 async nextQuestion(ok){const q=State.session.items[State.session.index].question,p={...Practice.getProgress(q.id)};p[ok?"correct":"incorrect"]++;p.lastAnswered=Date.now();await Practice.saveProgress(p);if(ok)State.session.correct++;await this.log("question",q.id,ok,q.type);State.session.index++;this.render()},
 finish(){Utils.$("session-progress").style.width="100%";Utils.$("session-content").innerHTML=`<article class="question-card center"><div class="hanzi">🎉</div><h2>Hoàn thành</h2><p>Bạn làm tốt ${State.session.correct}/${State.session.items.length} nội dung.</p><button class="full" onclick="State.session=null;App.showScreen('home')">Về trang Hôm nay</button></article>`;App.refresh()}
};
