
"use strict";
window.Vocabulary={
 getProgress(id){return State.wordProgress.get(id)||{wordId:id,repetitions:0,interval:0,ease:2.5,dueAt:0,correct:0,incorrect:0,favorite:false,mastered:false,lastStudied:0}},
 async saveProgress(p){State.wordProgress.set(p.wordId,p);await Storage.put(Storage.stores.wordProgress,p)},
 calculate(p,q){const n={...p};if(q<3){n.repetitions=0;n.interval=q===0?0:1;n.incorrect++}else{n.repetitions++;n.correct++;n.interval=n.repetitions===1?1:n.repetitions===2?3:Math.max(1,Math.round(n.interval*n.ease))}n.ease=Math.max(1.3,n.ease+(0.1-(5-q)*(0.08+(5-q)*0.02)));n.dueAt=Date.now()+n.interval*86400000;n.lastStudied=Date.now();n.mastered=n.repetitions>=4&&n.interval>=14;return n},
 activeWords(){const ids=new Set(State.vocabPacks.filter(p=>p.enabled!==false).map(p=>p.id)),lvl=Settings.currentLevel();return State.words.filter(w=>ids.has(w.packId)&&(lvl==="ALL"||w.level===lvl||(lvl==="HSK7-9"&&["HSK7","HSK8","HSK9","HSK7-9"].includes(w.level))))},
 resetFlashcards(){const pack=Utils.$("vocab-pack-filter").value||"all",filter=Utils.$("vocab-status-filter").value||"due";let a=this.activeWords();if(pack!=="all")a=a.filter(w=>w.packId===pack);if(filter==="due")a=a.filter(w=>this.getProgress(w.id).dueAt<=Date.now());if(filter==="new")a=a.filter(w=>!this.getProgress(w.id).lastStudied);if(filter==="weak")a=a.filter(w=>this.getProgress(w.id).incorrect>this.getProgress(w.id).correct);if(filter==="favorite")a=a.filter(w=>this.getProgress(w.id).favorite);State.flashQueue=a.length?a:this.activeWords();State.flashIndex=0;this.renderFlashcard()},
 renderFlashcard(){const w=State.flashQueue[State.flashIndex];if(!w){Utils.$("fc-hanzi").textContent="暂无";Utils.$("beginner-explanation").textContent="Chưa có từ phù hợp.";return}Utils.$("flashcard").classList.remove("flipped");Utils.$("fc-hanzi").textContent=w.hanzi;Utils.$("fc-pinyin").textContent=w.pinyin||"—";Utils.$("fc-meaning").textContent=w.meaning;Utils.$("fc-example").innerHTML=w.example?`${Utils.esc(w.example)}${w.exampleMeaning?`<br><small>${Utils.esc(w.exampleMeaning)}</small>`:""}`:"";Utils.$("favorite-btn").textContent=this.getProgress(w.id).favorite?"★ Đã yêu thích":"☆ Yêu thích";Utils.$("fc-counter").textContent=`${State.flashIndex+1}/${State.flashQueue.length}`;this.renderBeginner(w)},
 renderBeginner(w){if(State.settings.beginnerMode===false){Utils.$("beginner-explanation").innerHTML='<span class="muted">Chế độ người mới đang tắt.</span>';return}Utils.$("beginner-explanation").innerHTML=`<p><strong>Loại từ:</strong> ${Utils.esc(w.wordType||"Chưa ghi")}</p><p><strong>Cách dùng:</strong> ${Utils.esc(w.beginnerNote||"Hãy xem nghĩa và câu ví dụ để hiểu cách dùng.")}</p><p><strong>Mẹo nhớ:</strong> ${Utils.esc(w.memoryTip||"Chưa có mẹo nhớ.")}</p>${w.synonyms?.length?`<p><strong>Từ liên quan:</strong> ${w.synonyms.map(Utils.esc).join(" · ")}</p>`:""}`},
 flip(){Utils.$("flashcard").classList.toggle("flipped")},
 async rate(q){const w=State.flashQueue[State.flashIndex];if(!w)return;await this.saveProgress(this.calculate(this.getProgress(w.id),q));await Learning.log("word",w.id,q>=3,w.level);State.flashIndex=(State.flashIndex+1)%State.flashQueue.length;this.renderFlashcard();App.refresh()},
 async toggleFavorite(){const w=State.flashQueue[State.flashIndex];if(!w)return;const p={...this.getProgress(w.id),favorite:!this.getProgress(w.id).favorite};await this.saveProgress(p);this.renderFlashcard()},
 shuffle(){State.flashQueue=Utils.shuffle(State.flashQueue);State.flashIndex=0;this.renderFlashcard()},
 speak(){const w=State.flashQueue[State.flashIndex];if(!w||!("speechSynthesis"in window))return;const u=new SpeechSynthesisUtterance(w.hanzi);u.lang="zh-CN";u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u)},
 renderList(){const term=(Utils.$("vocab-search").value||"").toLowerCase(),packs=new Map(State.vocabPacks.map(p=>[p.id,p.name]));const a=this.activeWords().filter(w=>`${w.hanzi} ${w.pinyin} ${w.meaning} ${w.topic}`.toLowerCase().includes(term)).slice(0,400);Utils.$("vocab-count").textContent=`${a.length} từ`;Utils.$("vocab-list").innerHTML=a.map(w=>`<article class="data-item"><h4>${Utils.esc(w.hanzi)} <small>${Utils.esc(w.pinyin||"")}</small></h4><p>${Utils.esc(w.meaning)}</p><p>${Utils.esc(packs.get(w.packId)||"")} · ${Utils.esc(w.level||"")}</p><div class="item-actions"><button class="secondary" onclick="Vocabulary.openEditor('${w.id}')">Sửa</button><button class="danger" onclick="Vocabulary.deleteWord('${w.id}')">Xóa</button></div></article>`).join("")||'<p class="muted">Không tìm thấy từ.</p>'},
 openEditor(id=""){const w=State.words.find(x=>x.id===id);Utils.$("word-editor-title").textContent=w?"Sửa từ":"Thêm từ";Utils.$("word-id").value=w?.id||"";Utils.$("word-pack").innerHTML=State.vocabPacks.map(p=>`<option value="${p.id}">${Utils.esc(p.name)}</option>`).join("");Utils.$("word-pack").value=w?.packId||State.vocabPacks[0]?.id||"";["hanzi","pinyin","meaning","type","example","example-meaning","beginner-note","memory-tip","level","topic"].forEach(k=>{const map={"type":"wordType","example-meaning":"exampleMeaning","beginner-note":"beginnerNote","memory-tip":"memoryTip"};Utils.$(`word-${k}`).value=w?.[map[k]||k]||""});Utils.$("word-overlay").classList.add("open")},
 closeEditor(e){if(e&&e.target!==Utils.$("word-overlay"))return;Utils.$("word-overlay").classList.remove("open")},
 async saveEditor(){const id=Utils.$("word-id").value||Utils.uid("word"),packId=Utils.$("word-pack").value,w={id,packId,hanzi:Utils.$("word-hanzi").value.trim(),pinyin:Utils.$("word-pinyin").value.trim(),meaning:Utils.$("word-meaning").value.trim(),wordType:Utils.$("word-type").value.trim(),example:Utils.$("word-example").value.trim(),exampleMeaning:Utils.$("word-example-meaning").value.trim(),beginnerNote:Utils.$("word-beginner-note").value.trim(),memoryTip:Utils.$("word-memory-tip").value.trim(),level:Utils.$("word-level").value.trim(),topic:Utils.$("word-topic").value.trim()};if(!w.hanzi||!w.meaning)return Utils.toast("Chữ Hán và nghĩa là bắt buộc.");await Storage.put(Storage.stores.words,w);this.closeEditor();await Storage.loadAll();App.refresh();this.resetFlashcards();Utils.toast("Đã lưu từ.")},
 async deleteWord(id){if(!confirm("Xóa từ này?"))return;await Storage.remove(Storage.stores.words,id);await Storage.remove(Storage.stores.wordProgress,id);await Storage.loadAll();App.refresh();this.resetFlashcards()}
};
